from __future__ import annotations

from pathlib import Path

from gemla.pipelines import GemlaResult


def export_markdown_report(
    result: GemlaResult,
    output_path: str | Path,
    title: str = "GEMLA Transport Evaluation Report",
) -> Path:
    """
    Export a GEMLA evaluation result as a Markdown report.
    """
    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    main = result.gate_result["main"]
    controls = result.gate_result["controls"]

    text = f"""# {title}

## Final Verdict

**Verdict:** {"PASS" if result.verdict else "FAIL"}

## Main Branch

| Metric | Value |
|---|---:|
| RevA v2-SF pass | {main["pass"]} |
| Spectral flatness score | {main["flatness"]["score"]:.6f} |
| Phase growth | {main["metrics"]["phase_growth"]:.6f} |
| Orientation | {main["metrics"]["orientation"]:.6f} |
| Smoothness | {main["metrics"]["smoothness"]:.6f} |
| Curvature | {main["metrics"]["curvature"]:.6f} |
| Sign changes | {main["metrics"]["sign_changes"]} |

## Controls

| Control | Rejected | Pass |
|---|---:|---:|
| wrong_sign | {controls["wrong_sign"]["rejected"]} | {controls["wrong_sign"]["pass"]} |
| phase_shuffle | {controls["phase_shuffle"]["rejected"]} | {controls["phase_shuffle"]["pass"]} |
| residue_scramble | {controls["residue_scramble"]["rejected"]} | {controls["residue_scramble"]["pass"]} |

## Anchor Diagnostics

| Metric | Value |
|---|---:|
| Anchor count | {result.anchor_result["anchor_count"]} |
| Spacing mean | {result.anchor_result["spacing_mean"]:.6f} |
| Spacing std | {result.anchor_result["spacing_std"]:.6f} |
| Spacing CV | {result.anchor_result["spacing_cv"]:.6f} |

## Winding Diagnostics

| Metric | Value |
|---|---:|
| k min | {result.winding_result["k_min"]} |
| k max | {result.winding_result["k_max"]} |
| Total winding cells | {result.winding_result["total_winding_cells"]} |
| Jump count | {result.winding_result["jump_count"]} |
| Jump-gap CV | {result.winding_result["jump_gap_cv"]:.6f} |

## Interpretation

This report was generated by the minimal GEMLA vertical slice:

```text
synthetic trajectory
→ complex surrogate
→ lifted phase
→ RevA v2-SF gate
→ adversarial controls
→ anchor diagnostics
→ winding diagnostics
→ final verdict
```

The result should be interpreted as a finite diagnostic outcome on the supplied trajectory, not as a universal claim.
"""

    output_path.write_text(text, encoding="utf-8")
    return output_path